{% set name = "jupyter-fs" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dfd38c29de7c3f97923a5ece9aaa743454e83ce39c53a4d49ed689b4e09c43f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - jupyter-packaging
  run:
    - python >=3.7
    - fs >=2.4.11
    - fs-s3fs >=1.1.1
    - jupyterlab >=2.0.0
    - notebook >=5.7.0

test:
  imports:
    - jupyterfs

about:
  home: http://github.com/jpmorganchase/jupyter-fs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Filesystem-like multi-contents manager backend for Jupyter

  description: |
    A Filesystem-like mult-contents manager backend for Jupyter
  dev_url: https://github.com/jpmorganchase/jupyter-fs

extra:
  recipe-maintainers:
    - timkpaine
    - telamonian
